name: CD

on:
  push:
    branches:
      - 'main'

jobs:
  deploy_webapp:
    name: Deploy web app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd webapp
          yarn
          yarn build --base=/ec2-tracker

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: webapp/dist